// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlkqd45z34xYvY0DubwYcjmRPsySlHA_E',
    appId: '1:929654238475:web:0506bad496b4e300e9860e',
    messagingSenderId: '929654238475',
    projectId: 'bpgc-pawn-shop',
    authDomain: 'bpgc-pawn-shop.firebaseapp.com',
    storageBucket: 'bpgc-pawn-shop.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA5erx9-YJ5U8vDJ1Gu0M__PK7Vmdsb4U',
    appId: '1:929654238475:android:34467fcf1f5d7116e9860e',
    messagingSenderId: '929654238475',
    projectId: 'bpgc-pawn-shop',
    storageBucket: 'bpgc-pawn-shop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlhc7U3DTWaNUpkcrl1YPT74ZXJpVjI30',
    appId: '1:929654238475:ios:56d4f8d3941a2531e9860e',
    messagingSenderId: '929654238475',
    projectId: 'bpgc-pawn-shop',
    storageBucket: 'bpgc-pawn-shop.appspot.com',
    iosClientId: '929654238475-hv0unfvij2u14431om07mp0q336sgbep.apps.googleusercontent.com',
    iosBundleId: 'com.example.bpgcPawnShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlhc7U3DTWaNUpkcrl1YPT74ZXJpVjI30',
    appId: '1:929654238475:ios:07b2ee9eb56f43b1e9860e',
    messagingSenderId: '929654238475',
    projectId: 'bpgc-pawn-shop',
    storageBucket: 'bpgc-pawn-shop.appspot.com',
    iosClientId: '929654238475-5g113r4oisqho0gccmc5cl0fospasi4i.apps.googleusercontent.com',
    iosBundleId: 'com.example.bpgcPawnShop.RunnerTests',
  );
}
